import isBoolean from '../src/patterns/isBoolean'

it('should return true for valid boolean values', () => {
  expect(isBoolean(true)).toBe(true)
  expect(isBoolean(false)).toBe(true)
  expect(isBoolean('true')).toBe(true)
  expect(isBoolean('false')).toBe(true)
  expect(isBoolean()).toBe(false)
  expect(isBoolean(null)).toBe(false)
  expect(isBoolean('')).toBe(false)
  expect(isBoolean(' ')).toBe(false)
  expect(isBoolean('true ')).toBe(false)
  expect(isBoolean(' false')).toBe(false)
  expect(isBoolean('truefalse')).toBe(false)
  expect(isBoolean({})).toBe(false)
  expect(isBoolean([])).toBe(false)
  expect(isBoolean(1)).toBe(true)
  expect(isBoolean(0)).toBe(true)
  expect(isBoolean('1')).toBe(false)
})
