import isHash from '../src/patterns/isHash'

it('should return true for valid hash values', () => {
  expect(isHash('#abc')).toBe(true)
  expect(isHash('#ABC')).toBe(true)
  expect(isHash('#123')).toBe(true)
  expect(isHash('#abc123')).toBe(true)
  expect(isHash('#ABC123')).toBe(true)
  expect(isHash('#123abc')).toBe(true)
  expect(isHash('#123ABC')).toBe(true)
  expect(isHash('#123456')).toBe(true)
  expect(isHash('')).toBe(false)
  expect(isHash(' ')).toBe(false)
  expect(isHash('true')).toBe(false)
  expect(isHash('false')).toBe(false)
  expect(isHash()).toBe(false)
  expect(isHash(null)).toBe(false)
  expect(isHash(true)).toBe(false)
  expect(isHash(false)).toBe(false)
  expect(isHash({})).toBe(false)
  expect(isHash([])).toBe(false)
  expect(isHash(1)).toBe(false)
  expect(isHash(0)).toBe(false)
  expect(isHash('1')).toBe(false)
  expect(isHash('0')).toBe(false)
})
