import isString from '../src/patterns/isString'

it('should return true for valid string values', () => {
  expect(isString('abc')).toBe(true)
  expect(isString('')).toBe(true)
  expect(isString(' ')).toBe(true)
  expect(isString()).toBe(false)
  expect(isString(null)).toBe(false)
  expect(isString(true)).toBe(false)
  expect(isString(false)).toBe(false)
  expect(isString({})).toBe(false)
  expect(isString([])).toBe(false)
  expect(isString(1)).toBe(false)
  expect(isString(0)).toBe(false)
  expect(isString('1')).toBe(true)
  expect(isString('0')).toBe(true)
  expect(isString('1.1')).toBe(true)
  expect(isString('0.1')).toBe(true)
  expect(isString('1.1.1')).toBe(true)
  expect(isString('0.1.1')).toBe(true)
})
